# Numpy exercises


#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [2]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [15]:
arr=np.zeros(10,dtype=np.int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [13]:
?np.add

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [16]:
arr[5]=1
arr

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#### 5.  Create a vector with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [20]:
a1=np.arange(10,50)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [25]:
a2=np.arange(0,51)
s=slice(51,0,-1)
a2[s]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [28]:
a3=np.arange(0,9)
a3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [63]:
a4=np.array([1,2,0,0,4,0])
for i in range(len(a4)):
    if a4[i]!=0:
        print(i)

0
1
4


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [36]:
a5=np.random.randint(1,20,3*3*3).reshape(3,3,3)
a5

array([[[ 6,  1,  4],
        [ 3, 14,  4],
        [12,  9, 12]],

       [[ 9,  6, 15],
        [ 9,  5,  6],
        [ 7, 16,  6]],

       [[ 1, 14, 12],
        [19, 14, 14],
        [19, 17, 13]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [53]:
a6=np.random.rand(10,10)
#print(a6)
print("Minimal value: ",a6.min())
print("Maximal value: ",a6.max())

Minimal value:  0.02786953458583663
Maximal value:  0.9799183997456584


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [57]:
a7=np.random.rand(30)
#print(a7)
print(a7.mean())

0.5774041557313784


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [78]:
a8=np.arange(0,11)
a8[(a8>3) & (a8<8)]

array([4, 5, 6, 7])

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [91]:
a9=np.random.randint(1,10,20)
print(a9)
print(a9[a9<5]*2)

[6 6 9 5 1 3 2 3 8 2 7 4 8 4 8 6 5 5 6 3]
[2 6 4 6 4 8 8 6]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [94]:
a10=np.array([1, 5, 6, 2, -2, 23, 45])
a10[a10%2==0]

array([ 6,  2, -2])

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [101]:
a11=np.arange(1,21)
a11[a11%3==0]

array([ 3,  6,  9, 12, 15, 18])

#### 16. Create a 5x5 matrix with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [110]:
a12=np.arange(0,5)
a13=np.tile(a12,5)
a13.reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 17. Գեներացրեք 1-ից 10 պատահական թվեր ու ստեղծեք (3, 5) չափերով numpy array-ը

In [113]:
a14=np.random.randint(1,10,3*5).reshape(3,5)
a14

array([[8, 3, 1, 1, 8],
       [9, 4, 8, 6, 5],
       [1, 2, 5, 9, 2]])

#### 18. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [116]:
a15=np.zeros(10,dtype=int)
a15[5]=3
a15

array([0, 0, 0, 0, 0, 3, 0, 0, 0, 0])

#### 19. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [118]:
a16=np.arange(3,15)
a16

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 20. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [148]:
def func(arr):
    if arr.mean()<=5:
        return arr
    return func(arr/2)    
    
a17=np.arange(1,30)
print(func(a17))
    

[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5
 3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.
 7.25]


#### 21. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [157]:
a18=np.random.randint(1,10,20).reshape(5,4)

print(a18)

def raws(arr):
    return arr[0,...],arr[1,...],arr[2,...],arr[3,...],arr[4,...]

def columns(arr):
    return arr[...,0],arr[...,1],arr[...,2],arr[...,3]

print(raws(a18))

print(columns(a18))
    



[[6 8 8 2]
 [9 8 2 3]
 [6 3 8 9]
 [6 2 8 5]
 [4 5 3 9]]
(array([6, 8, 8, 2]), array([9, 8, 2, 3]), array([6, 3, 8, 9]), array([6, 2, 8, 5]), array([4, 5, 3, 9]))
(array([6, 9, 6, 6, 4]), array([8, 8, 3, 2, 5]), array([8, 2, 8, 8, 3]), array([2, 3, 9, 5, 9]))
