In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,10,(5,3))
a

array([[3, 8, 8],
       [9, 9, 6],
       [7, 8, 5],
       [2, 2, 6],
       [1, 3, 1]])

In [4]:
b=np.zeros(10)
b[5]=3
b

array([0., 0., 0., 0., 0., 3., 0., 0., 0., 0.])

In [5]:
c=np.arange(3,15)
c

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
d=np.array([1,3,5,2,4,5])
print(d.reshape(3,2))
print()
print(d.reshape(2,3))

[[1 3]
 [5 2]
 [4 5]]

[[1 3 5]
 [2 4 5]]


In [54]:
def func1(nparr):
    if nparr.mean()<=5:
        return nparr
    else:
        return func1(nparr/2)
        


x=np.arange(1,20)
print(x)
func1(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [46]:
x=np.random.randint(1,10,10)
x.mean()

4.9

In [34]:
def func2(nparr):
    l=[]
    for i in range(4):
        l.append(nparr[::,i])
    return l
    
    
x=np.random.randint(1,10,(5,4))
print(x)
print()
print(func2(x))

[[1 9 8 4]
 [8 3 1 6]
 [8 2 3 2]
 [7 8 1 6]
 [6 6 5 8]]

[array([1, 8, 8, 7, 6]), array([9, 3, 2, 8, 6]), array([8, 1, 3, 1, 5]), array([4, 6, 2, 6, 8])]


In [41]:
def func3(nparr):
    l=[]
    for i in range(5):
        l.append(nparr[i,::])
    return l
    
    
x=np.random.randint(1,10,(5,4))
print(x)
print()
print(func3(x))

[[7 5 5 4]
 [4 2 1 9]
 [3 7 3 8]
 [7 2 3 7]
 [1 3 5 3]]

[array([7, 5, 5, 4]), array([4, 2, 1, 9]), array([3, 7, 3, 8]), array([7, 2, 3, 7]), array([1, 3, 5, 3])]
